function BlockFall(h,evt)
global block background

index = [block.core; block.peri];
if      background(index(1,1)+1,index(1,2)) + ...
        background(index(2,1)+1,index(2,2)) + ...
        background(index(3,1)+1,index(3,2)) + ...
        background(index(4,1)+1,index(4,2)) + ...
        background(index(1,1),index(1,2)) + ...
        background(index(2,1),index(2,2)) + ...
        background(index(3,1),index(3,2)) + ...
        background(index(4,1),index(4,2)) == 0
    block.core = block.core + [1 0];
else
    destroy_block();
    line_clearance();
    block_definition();
end

refresh_block();
plot_background();
plot_block();
end